// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnnslxokzixauvyxzoch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubnNseG9reml4YXV2eXh6b2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDIyMTUsImV4cCI6MjA2MzE3ODIxNX0.LJI6mKMhn_-sAo-ShyV7ACN4AgCFA9KU2kfS9Hv0U6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);